### ISSUE TITLE
In case I have an issue: is this project still monitored / maintained?

### ISSUE THREAD

**Issue by bm765** [aklxao2/SDR#1]
Hi,

I started to look a little bit into this package.

I am unsure whether somebody is still taking care for questions or issues for this project.

Background: in case nobody is really maintaining it anymore, I would shift my efforts to other - similar - projects. 

Thanks in advance!

**Comment by agvico** [comment]
Hi, thanks for opening this question, it is great to know that people is interested in this package.

Unfortunately, I'm not actively maintaining the project as it needs a deep revision and I don't too much time for that, but I would be happy to answer any question you have.

Cheers

**Comment by bm765** [comment]
Hi,

thanks for letting me know. :-)

If I come to the point where a question comes up, I will post it here accordingly!
